# Uncomment the next line to apply a theme; see more on https://github.com/pages-themes
# theme: jekyll-theme-cayman

# Website title
title : Simulation Optmization Code Gallery 

# Author information
author : SHEN Haihui
email: shenhaihui@gmail.com
